attackgoat/screen-13

- src/driver/swapchain.rs
Fixes swapchain recreation not updating its own info's bounds, this caused `present2` to launch with an invalid invocation size, which made any resized areas black. Resizing seems to work fine now, however, old resources leftover from resizing will not be dropped, this is not ideal because it is leaking memory. My thought for resolving this is doing something similar to what granite does, making image size an enum of either "swapchain-relative" or "absolute" then doing the culling... somewhere.
> Fix: fix swapchain not updating its image extents upon recreation/resize

- examples/fuzzer.rs
- src/driver/compute.rs
- src/driver/device.rs
- src/driver/graphic.rs
- src/driver/mod.rs
- src/driver/ray_trace.rs
- src/driver/shader.rs
- src/graph/resolver.rs
This change:
- Provides descriptor indexing info on `Device` so programs can know if hardware supports bindless
- Allows shaders (compute/graphic/ray trace) to specify unbounded arrays
- Adds example/test code in `fuzzer.rs`
- Fixes an unrelated bug in the "wont merge" fuzzer test case
Programs that want to use bindless will need to understand that when it is not available they should provide a bounded-option; but this change does not address documentation which is lacking overall.
> Bindless support

- src/graph/mod.rs
- src/graph/node.rs
- src/graph/pass_ref.rs
- src/graph/resolver.rs
Since vk::ClearValue and vk::ClearColorValue are unions it is not possible to print them with debug. I added a simple enum and added Debug to Color and Execution. Since only the float32 field of the vk::ClearColorValue is used I haven't added an enum for it.
> ClearValue as rust enum.

- examples/ray_trace.rs
- src/driver/mod.rs
- src/driver/ray_trace.rs
I hope the formatting is correct this time.
Should the shader group handlers be their own type? This way one could guarantee alignment.
Anyway, got myself a rtx card so I'm experimenting with ray tracing at the moment. Your library makes that pretty convenient. Thanks.
> Added helper function to get shader_group_handles to RayTracePipeline.

- contrib/screen-13-fx/src/bitmap_font.rs
- examples/fuzzer.rs
- examples/ray_trace.rs
- src/display.rs
- src/driver/accel_struct.rs
- src/driver/device.rs
- src/graph/pass_ref.rs
- src/graph/resolver.rs
- src/input/typing.rs
Adds a fuzzer test which demonstrates one correct way of generating a bunch of bottom-level acceleration structures in a frame and building their top-level acceleration structure later in the same frame.
> Acceleration structure build dependencies test

- contrib/screen-13-fx/src/bitmap_font.rs
- contrib/screen-13-fx/src/image_loader.rs
- examples/egui.rs
- examples/imgui.rs
- examples/multipass.rs
- examples/ray_trace.rs
- examples/shader-toy/src/main.rs
- src/display.rs
- src/driver/descriptor_set.rs
- src/driver/device.rs
- src/driver/mod.rs
- src/driver/render_pass.rs
- src/event_loop.rs
- src/graph/binding.rs
- src/graph/edge.rs
- src/graph/mod.rs
- src/graph/node.rs
- src/graph/resolver.rs
- src/lib.rs
- src/pool/hash.rs
- src/pool/lazy.rs
- src/pool/mod.rs
This change is intended to improve the usability of _Screen 13_ by letting users choose different cache strategies for different parts of their render graph. Leasing resources (automatic lifetime management) will remain the central concept but the types of leases available will be new.
Currently _Screen 13_ provides a single `HashPool` type which provides resource leases using the `PartialEq` trait. More advanced cases might use a algorithm that fits existing resources to the requests at hand - for example leasing a buffer that is larger than required but avoids constructing a new one.
**TODO**
> Improve resource pool/leasing API

- src/driver/swapchain.rs
- src/event_loop.rs
Fixes #35
The `swapchain` handle was kept after destroy, and later used as part of the recreate function.
TODO:
> Fix for accessing destroyed swapchain

- CHANGELOG.md
- Cargo.toml
- src/driver/shader.rs
Your current code won't compile because `spirq>=0.6.2` is too relaxed btw
> Upgrade from spirq 0.6.2 to 1.0.0

- CHANGELOG.md
- Cargo.toml
- contrib/screen-13-egui/Cargo.toml
- contrib/screen-13-egui/src/lib.rs
- contrib/screen-13-hot/examples/glsl.rs
- contrib/screen-13-imgui/Cargo.toml
- contrib/screen-13-imgui/src/lib.rs
- examples/egui.rs
- examples/imgui.rs
- examples/ray_trace.rs
- examples/rt_triangle.rs
- examples/transitions.rs
- examples/vsm_omni.rs
- src/driver/buffer.rs
- src/driver/device.rs
- src/driver/mod.rs
- src/driver/surface.rs
- src/driver/swapchain.rs
- src/event_loop.rs
- src/frame.rs
- src/input/key_buf.rs
- src/input/key_map.rs
- src/input/mod.rs
- src/input/mouse_buf.rs
- src/lib.rs
This works but I'm going to wait for official releases of `egui` and `imgui-rs` containing the following PRs:
> Update to winit 0.29

- examples/msaa.rs
- examples/vsm_omni.rs
- src/lib.rs
- src/pool/fifo.rs
- src/pool/hash.rs
- src/pool/lazy.rs
- src/pool/mod.rs
The pool types have the ability to grow and eventually use up all available resources.
This can be reproduced using the MSAA example or any other code which leases resources dependent on the swapchain size and then continuously resizing the window in order to generate many requests for resources with different sizes.
This is related to but not necessarily the entire fix for #69.
Additionally, there should be a new pool type which focuses on using the least possible memory overall.
> Improve pool memory management

- CHANGELOG.md
- Cargo.toml
- contrib/rel-mgmt/run-all-examples
- examples/image_sampler.rs
- src/driver/descriptor_set.rs
- src/driver/graphic.rs
- src/driver/shader.rs
- src/graph/resolver.rs
- src/pool/fifo.rs
- src/pool/lazy.rs
Adds GLSL and HLSL support for separate image samplers.
Resolves #72
> Add support for separate image samplers

- src/driver/graphic.rs
- src/driver/shader.rs
- src/graph/resolver.rs
The image_sampler example with `--separate` (with either hlsl or glsl) was resulting in this vulkan validation error:
```
VUID-VkWriteDescriptorSet-descriptorType-02752(ERROR / SPEC): msgNum: -1422077154 - Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-02752 ] Object 0: handle = 0x625f640000000058, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; 
| MessageID = 0xab3cd31e | vkUpdateDescriptorSets(): pDescriptorWrites[1] Attempted write update to an immutable sampler descriptor. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_SAMPLER, then dstSet must not have been allocated with a layout that included immutable samplers for dstBinding (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-02752)
```
It …
> Fix: Attempted write update to an immutable sampler descriptor.

- src/display.rs
Would it be possible to allow for resolve/submit on a different thread?
I'm currently using this to get some initial pipelined rendering working where the graph is built on one thread and then resolved/submitted on another.
Here's a screenshot from tracy with before and after.
> Make ResolverPool send to allow for resolve/submit on a different thread.

- src/graph/resolver.rs
Framebuffer attachments should always be matched with the same image:
```rust
RenderGraph::new()
.begin_pass("My Graphic Pass")
.bind_pipeline(&my_graphic_pipeline)
.clear_color(0, swapchain_image)
.store_color(0, swapchain_image)
```
And in the case of merged render passes they will always having matching formats and sample counts because `Attachment::are_identical()` checks that they are in fact the same image.
With this logic it is safe to set the format, sample count, and initial layout on framebuffer load operations and then also set the format and sample count in addition to final layout on store operations. In cases where the user does not specify a load or store operation we can infer the format. This fixes the issue of depth images having the wrong layout due to it being set …
> Fix for incorrect framebuffer attachment handling

- README.md
#75 moved `hello_world.rs` to a different location without updating the `README.md` file; this PR fixes that oversight.
> Fix `hello_world.rs` link in `README.md`

- Cargo.toml
- contrib/screen-13-window/src/lib.rs
- examples/app.rs
- examples/cpu_readback.rs
- examples/msaa.rs
- examples/multipass.rs
- examples/ray_omni.rs
- examples/subgroup_ops.rs
- examples/vsm_omni.rs
- src/display.rs
- src/driver/cmd_buf.rs
- src/driver/device.rs
- src/driver/image.rs
- src/driver/instance.rs
- src/driver/surface.rs
- src/driver/swapchain.rs
- src/graph/resolver.rs
- src/graph/swapchain.rs
- src/lib.rs
Modifies the `Display` struct to own a `Swapchain`, instead of operating in conjunction with it. Fixes the incorrect "image ready" fence which was waited upon before submitting new frames.
_The previous behavior was unsound and only worked on certain hardware._
The new pattern greatly simplifies swapchain handling:
- A list of command buffers available to execute frame submissions is kept in `Display`
- The list of command buffers may have 1 or more items, up to and beyond the number of swapchain images
Process:
- `vkAcquireNextImageKHR` signals an "acquire" semaphore when the image is available
- Rendering commands wait for "acquire" and signal a "rendered" semaphore
- `vkQueuePresentKHR` waits for "rendered" before presenting the image
Additionally, recreating the swapchain no longer …
> Swapchain performance/correctness

- src/driver/swapchain.rs
- src/graph/resolver.rs
Fixes #96 - Not sure if this is a good solution, but it removed all validation errors and most examples seem to be working. 
Tested on linux with:
```
apiVersion         = 1.4.305
driverVersion      = 25.0.1
vendorID           = 0x1002
deviceID           = 0x744c
deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
deviceName         = AMD Radeon RX 7900 GRE (RADV NAVI31)
driverID           = DRIVER_ID_MESA_RADV
driverName         = radv
driverInfo         = Mesa 25.0.1
conformanceVersion = 1.4.0.0
```
> fix: missing access for the present transition and fix crash due to missing active extension

- src/driver/instance.rs
- src/driver/swapchain.rs
Vulkan can always return more images than provided in ``.min_image_count(..)``.
Ref: https://gitlab.freedesktop.org/apinheiro/mesa/-/issues/9
Quotes by a comment in that issue:
From the Vulkan spec: minImageCount is the minimum number of presentable images that the application needs. The implementation will either create the swapchain with at least that many images(...)
> fix: remove debug assert for desired image count and set_var fix

- src/driver/swapchain.rs
Hi,
this PR is more like a request for comments than an a proper actual fix.
I noticed on Mac OSX, some of the examples may crash when their windows is being resized. The example `egui` seems particularly prone to that issue.
the debugger shows that the segfault always happens in the following function:
```
; Symbol: MVKSwapchain::beginPresentation(MVKImagePresentInfo const&), mangled name=_ZN12MVKSwapchain17beginPresentationERK19MVKImagePresentInfo
```
I found this issue on MoltenVK's repo: https://github.com/KhronosGroup/MoltenVK/issues/2031
which seems to imply that  `vkDeviceWaitIdle()` should be called when a resize is being detected.
Therefore, I added a call to `device.device_wait_idle()` just before destroying the old swap_chain, and that seems quite successful on my side so far. …
> fix: add device_wait_idle when destroying swapchain

- src/driver/mod.rs
- src/graph/mod.rs
Added support for block formats in `format_texel_block_size()`, `copy_buffer_to_image_regions()`, `copy_image_to_buffer_regions()`. Added `format_texel_block_dimensions()`.
Added remaining formats in https://registry.khronos.org/vulkan/specs/latest/html/vkspec.html#texel-block-size
Have only tested with BCn textures.
> Block format support

- contrib/screen-13-window/src/lib.rs
- src/driver/swapchain.rs
Sometimes a bit more flexibility is needed here than just vsync on/off for testing, and occasionally in video games players may also want more control.
Inspired by https://github.com/gfx-rs/wgpu/blob/v25/wgpu-types/src/lib.rs#L5125 but didn't include `AutoVsync` or `AutoNoVsync`, and rather opted for making all of the modes non-fallible with appropriate fallback options.
Didn't update `WindowData` or `WindowBuilder` in this PR since I wanted to get your opinion first on the general direction first. (I also don't personally use `WindowData` or `WindowBuilder` so I wouldn't need a change with those to accomplish what I'm trying to do)
> Make present mode configurable
